# Generated by Django 5.2.9 on 2026-01-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.admin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='exam_submissions/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examsubmission')),
            ],
        ),
    ]
